pipeline:
  identifier: Build_hrseber_jhttp_1737584933594
  name: Build jhttp
  orgIdentifier: default
  projectIdentifier: Rudy
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1737569394802
        repoName: hrseber/jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
                contextType: Pipeline
              - step:
                  name: Java Test
                  identifier: Java_Test
                  template:
                    templateRef: Rudy_Java_Test
                    versionLabel: "1"
                    type: JUnit
                    spec:
                      paths:
                        - /path/to/test/report.xml
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_2
                  identifier: BuildAndPushDockerRegistry_2
                  spec:
                    connectorRef: account.harnessImage
                    repo: hrseber/harness
                    tags:
                      - fabio
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: K8sCanaryDeploy
                  name: "Canary Deployment "
                  identifier: K8sCanaryDeploy_1
                  spec:
                    skipDryRun: false
                    instanceSelection:
                      type: Count
                      spec:
                        count: 1
                  timeout: 10m
              - step:
                  type: K8sCanaryDelete
                  name: Canary Delete
                  identifier: Canary_Delete
                  spec: {}
                  timeout: 10m
              - step:
                  type: K8sRollingDeploy
                  name: Rolling Deployment
                  identifier: Rolling_Deployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: harnessguestbookdep
          environment:
            environmentRef: harnessdevenvdep
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradep
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  flowControl:
    barriers: []
